config/routes.rb
Rails.application.routes.draw do
    resources :enquirys, only: [:new, :create, :index, :destroy, :edit] do
    resources :steps, only: [:show, :update], controller: 'enquirys/steps'
  end
 
  root to: 'enquirys#index'

end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
	 #ophalen van andere tabellen voor het formulier. Has_many is 1 op veel relatie
   #accepts_nested_attributes Nested attributes allow you to save attributes on associated records through the paren
# de dere regel zorgt ervoor dat de maatregelen worden opgehaald via de tussentabel enquiry_measures. 

  has_many :enquiry_measures, :class_name => 'EnquiryMeasure'#, inverse_of: :Enquiry
  accepts_nested_attributes_for :enquiry_measures, :allow_destroy => true

  has_many :measures, -> { uniq }, :class_name => 'Measure', :through => :enquiry_measures, dependent: :destroy

# 28-11 MG de pagina's die in het form worden gebruikt.
  cattr_accessor :form_steps do
    %w(basic when measurements)
  end

  attr_accessor :form_step

  validates :Reference, :Location, presence: true, if: -> { required_for_step?(:basic) }
  validates :Amount, :Date, presence: true, if: -> { required_for_step?(:when) }
  #validates :needed, presence: true, if: -> { required_for_step?(:measurements) }

  def required_for_step?(step)
    return true if form_step.nil?
    return true if self.form_steps.index(step.to_s) <= self.form_steps.index(form_step)
  end


end

app/models/enquiry_measure.rb
class EnquiryMeasure < ActiveRecord::Base
	belongs_to :enquiry, :class_name => 'Enquiry' #, inverse_of: :enquiry_measures
 		 validates_presence_of :enquiry
	has_many :measure, :class_name => 'Measure'
end

app/models/measure.rb
class Measure < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 #voor het inloggen 28/11 MG
  helper_method :current_user

end

app/controllers/enquirys/steps_controller.rb
class Enquirys::StepsController < ApplicationController
include Wicked::Wizard
  steps *Enquiry.form_steps
  
  def show
    @enquiry = Enquiry.find(params[:enquiry_id])
    render_wizard
  end

  def update
    @enquiry = Enquiry.find(params[:enquiry_id])
    @enquiry.update(enquiry_params(step))
    render_wizard @enquiry
  end

  private

  def enquiry_params(step)
    permitted_attributes = case step
                           when "basic"
                             [:Reference, :Location, :Description]
                           when "when"
                             [:Amount, :Date]
                           when "measurements"
                            [:responsible]
                           end

    params.require(:enquiry).permit(permitted_attributes).merge(form_step: step)
  end

end

app/controllers/enquirys_controller.rb
class EnquirysController < ApplicationController
	before_action :set_enquiry, only: [:show, :edit, :update, :destroy]

	def index
    # Normally you'd have more complex requirements about
    # when not to show rows, but we don't show any records that don't have a name
    @enquirys = Enquiry.where.not(reference: nil)
def new
  @enquiry = Enquiry.new
 
	end
		
	   def create
    @enquiry = Enquiry.new
    @enquiry.save(validate: false)
    redirect_to enquiry_step_path(@enquiry, Enquiry.form_steps.first)
	end

	def show
		@enquiry = Enquiry.find(params[:enquiry_id])
		render_wizard
	end

 def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquirys_url }
      format.json { head :no_content }
    end
  end

end

#24/11 MG opslaan van url voor terug knop:


 private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #Nodig voor het opslaan en tonen van items! alle weer te geven dingen dienen in de params te staan.
    def enquiry_params
      params.require(:enquiry).permit(:Reference, :Location, :Date, :Time, :Amount)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcomeindex
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#voor het aanmaken van een nieuwe gebruiker 28/11  MG
	  def show_field_error(model, field)
    s=""

    if !model.errors[field].empty?
      s =
        <<-EOHTML
           <div id="error_message">
             #{model.errors[field][0]}
           </div>
        EOHTML
    end

    s.html_safe
  end
end

app/helpers/enquirys/steps_controller_helper.rb
module Enquirys::StepsControllerHelper
end

app/helpers/enquirys/steps_helper.rb
module Enquirys::StepsHelper
end

app/helpers/enquirys_helper.rb
module EnquirysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/enquiry/steps/basic.html.erb
<h1>Deze map word niet gebruikt lijkt het!!!!! werkt niet</h1>


<%= form_for @enquiry, method: :put, url: wizard_path do |f| %>
  <% if f.object.errors.any? %>
    <div class="error_messages">
      <% f.object.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <legend>Enquiry Basic</legend>

    <div>
      <%= f.label :reference %>
      <%= f.text_field :reference %>
    </div>

    <div>
      <%= f.label :Location %>
      <%= f.text_field :location %>
    </div>


    <div>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>


    <div>
      <%= f.submit 'Next Step' %>
    </div>
  </fieldset>
<% end %>

app/views/enquiry/steps/instructions.html.erb
<%= form_for @pet, method: :put, url: wizard_path do |f| %>
  <% if f.object.errors.any? %>
    <div class="error_messages">
      <% f.object.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <legend>Instructions</legend>

    <div>
      <%= f.label :special_instructions %>
      <br />
      <%= f.text_area :special_instructions, rows: 10 %>
    </div>

    <div>
      <%= f.submit 'Next Step' %>
    </div>
  </fieldset>
<% end %>

app/views/enquiry/steps/when.html.erb
<%= form_for @enquiry, method: :put, url: wizard_path do |f| %>
  <% if f.object.errors.any? %>
    <div class="error_messages">
      <% f.object.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <legend>Enquiry </legend>

    <div>
      <%= f.label :amount %>
      <br />
      <%= f.text_area :amount, rows: 10 %>
    </div>

    <div>
      <%= f.label :date%>
      <%= f.text_field :date %>
    </div>

    <div>
      <%= f.label :time%>
      <%= f.text_field :time %>
    </div>

    <div>
      <%= f.submit 'Next Step' %>
    </div>
  </fieldset>
<% end %>

app/views/enquirys/_form.html.erb
<%= form_for(@enquiry) do |f| %>
  <% if @enquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enquiry.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @enquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :reference %>
      <%= f.text_field :Reference %>
    </div>

    <div class="field">
      <%= f.label :Location %>
      <%= f.text_field :Location %>
    </div>


    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :Description %>
    </div>

  <div class="field">
      <%= f.label :amount %>
      <br />
      <%= f.text_area :Amount, rows: 10 %>
    </div>

      <div class="field">>
      <%= f.label :date%>
      <%= f.text_field :Date %>
    </div>

      <div class="field">
      <%= f.label :time%>
      <%= f.text_field :Time %>
    </div>
<%# 24/11 MG vanaf hier zijn de extra tabellen toegevoegd. bovenstaande werkt!!! -%>

      <div class="field">
      <%= f.label :Done %>
      <%= enquiry_measures.text_field :done %>
    </div>

      <div class="field">
      <%= f.label :Needed %>
      <%= enquiry_measures.text_field :needed %>
    </div>


<%# 24/11 MG tot hier-%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enquirys/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquirys_path %>
 

app/views/enquirys/index.html.erb
<h1>Listing enquirys</h1>


<table>
  <thead>
    <tr>
      <th>referentie</th>
      <th>Beschrijving</th>
      <th>Locatie</th>
      <th>Datum</th>
      <th>Aantal uitvoerenden</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @enquirys.each do |enquiry| %>
      <tr>
        <td><%= enquiry.Reference %></td>
        <td><%= enquiry.Description %></td>
        <td><%= enquiry.Location %></td>
       <td><%= enquiry.Date %></td>
       <td><%= enquiry.Amount %></td>
      
        <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Weet u zeker dat u deze record wilt verwijderen?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nieuwe werkvergunning', enquirys_path, method: :create %>
<br>



<% if false %>
<td><%= simple_format enquiry.Date %></td>  
<td><%= simple_format enquiry.Amount %></td>
<% end %>

app/views/enquirys/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', enquirys_path %>

app/views/enquirys/steps/basic.html.erb
<%= form_for @enquiry, method: :put, url: wizard_path do |f| %>
  <% if f.object.errors.any? %>
    <div class="error_messages">
      <% f.object.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <fieldset class= "enquiry">
    <legend>Enquiry Basic</legend>

    <div>
      <%= f.label :reference %>
      <%= f.text_field :Reference %>
    </div>

    <div>
      <%= f.label :Location %>
      <%= f.select :Location, [['Chemiepark','chemiepark'],['Farmsum','farmsum'],['Winschoten','winschoten']] %>
    </div>


    <div>
      <%= f.label :description %>
      <%= f.text_area :Description %>
    </div>


    <div>
      <%= f.submit 'Next Step' %>

      <%# 24-11 MG knop die je terug stuurt naar de homepage %>
      <%= button_tag "Annuleren", :type => 'button', :class => "subBtn", :onclick => "location.href = '#{root_path()}'" %>
   
    </div>
   
  </fieldset>

<% end %>

app/views/enquirys/steps/measurements.html.erb
<%= form_for @enquiry, method: :put, url: wizard_path do |f| %>
  <% if f.object.errors.any? %>
    <div class="error_messages">
      <% f.object.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <legend>Maatregelen</legend>
       <%= f.fields_for :enquiry_measures do |enquiry_measures| %>
                                <%= enquiry_measures.fields_for :measure do |measures| %>
    <div>
      <%= f.label :Maatregel %>
      <br />
      <%= collection_select(:measure, :enquiry_id, Enquiry.all, :id, :measurement) %>
     <%# http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-collection_select -%>
    </div>
     <div>
      <%= f.label :Gereed %>
      <br />
      <%= enquiry_measures.text_field :done %>
    </div>

    <div>
      <%= f.label :Verantwoordelijke %>
      <br />
      <%= enquiry_measures.text_field :responsible %>
    </div>

    <div>
      <%= f.label :Benodigd %>
      <br />
      <%= enquiry_measures.text_field :needed %>
    </div>       
                    
    <div>
      <%= f.submit 'Next Step' %>
    </div>

          <% end %> <%# end of enquiry_measures.fields_for :measure %>
    <% end %> <%# end of f.fields_for :enquiry_measures %>
  </fieldset>
<% end %>

app/views/enquirys/steps/when.html.erb
<%= form_for @enquiry, method: :put, url: wizard_path do |f| %>
  <% if f.object.errors.any? %>
    <div class="error_messages">
      <% f.object.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <legend>Enquiry </legend>

    <div>
      <%= f.label :uitvoerenden  %>
      <%= f.number_field :Amount, rows: 10 %>
    </div>

    <div>
      <%= f.label :date%>
      <%= f.date_select :Date %>
    </div>

    <div>
      <%= f.label :Time%>
      <%= f.time_select :Time %>
    </div>

    <div>
      <%= f.submit 'Next Step' %>
          <%# knop naar vorige pagina %>
      <%= button_to "vorige", enquirys_path %>

  <%# 24-11 MG knop die je terug stuurt naar de homepage %>
      <%= button_tag "Annuleren", :type => 'button', :class => "subBtn", :onclick => "location.href = '#{root_path()}'" %>

    </div>


  </fieldset>
<% end %>

app/views/enquirys_oud/create.html.erb
<h1> werkvergunning aangevraagd!</h1>

<%= link_to 'Terug', new_enquiry_path %>

app/views/enquirys_oud/new.html.erb
<h1> nieuwe werkvergunning </h1>
<hr>
<%= form_for :enquiry, url: enquirys_path do |f| %>
<p>
	<%= f.label "Referentie" %>
	<%= f.text_field :Reference %>
</p>
<p>
	<%= f.label "Opmerking" %>
	<%= f.text_area :Description %>
</p>

<p>
	<%= f.label "Locatie:" %>
	<%= f.select :Location, [['Chemiepark','chemiepark'],['Farmsum','farmsum'],['Winschoten','winschoten']] %>
</p>

<p>
	<%= f.label "Aantal uitvoerenden" %>
	<%= f.number_field :Amount %>
</p>

<p>
	<%= f.label "Datum" %>
	<%= f.date_select :Date %>
</p>
<p>
	<%= f.label "Aanvangstijd" %>
	<%= f.time_select :Time %>
</p>

<p>
	<%= f.submit "Verzenden" %>
</p>
<% end %> 	

<%= link_to 'Terug', enquirys_path %>

app/views/enquirys_oud/overzicht.html.erb
<table>
	<tr>
		<th>Referentie</th>
		<th>Opmerking</th>
	</tr>

	<% @enquirys.each do |enquiry| %>
	<tr>
		<td><%= enquiry.Reference %></td>
		<td><%= enquiry.Description %> </td>
	</tr>
	<% end %>
</table>

app/views/enquirys_oud/steps/basic.html.erb
%= form_for @enquiry, method: :put, url: wizard_path do |f| %>
  <% if f.object.errors.any? %>
    <div class="error_messages">
      <% f.object.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <legend>Enquiry basic</legend>

    <div>
      <%= f.label :Reference %>
      <%= f.text_field :reference %>
    </div>

    <div>
      <%= f.label :location %>
      <%= f.select :Location, [['Chemiepark','chemiepark'],['Farmsum','farmsum'],['Winschoten','winschoten']] %>
    </div>

    <div>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>


    <div>
      <%= f.submit 'Next Step' %>
    </div>
  </fieldset>
<% end %>

app/views/enquirys_oud/steps/show.html.erb
<h1>Enquirys::Steps#show</h1>
<p>Find me in app/views/enquirys/steps/show.html.erb</p>

app/views/enquirys_oud/steps/update.html.erb
<h1>Enquirys::Steps#update</h1>
<p>Find me in app/views/enquirys/steps/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Werkvergunning</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
  <% if current_user %>
  <% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>
<% end %>
</body>

</html>

app/views/welcome/welcomeindex.html.erb
<h1>Welcome#welcomeindex</h1>
<p>Find me in app/views/welcome/welcomeindex.html.erb</p>